select top 5 * from dbo.customer;

-- Q1. What is the revenue generated by male vs. female customers?

SELECT GENDER, SUM(PURCHASE_AMOUNT) AS REVENUE FROM dbo.customer GROUP BY GENDER;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount 
from dbo.customer 
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from dbo.customer);

-- Q3. Which are the top 5 products with highest average review rating?

select top 5 item_purchased, round(avg(review_rating), 2) as average_rating 
from dbo.customer 
group by item_purchased
order by avg(review_rating) desc;

-- Q4. Compare the average purchase amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount), 2) as average_purchase_amount 
from dbo.customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribed and non-subscribers.

select subscription_status, count(customer_id), 
avg(purchase_amount) as average_spend,
sum(purchase_amount) as total_revenue
from dbo.customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased, 
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as discount_rate
from dbo.customer
group by item_purchased
order by discount_rate desc;

-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases, 
(case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end) as customer_segment
from dbo.customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8. What are 3 top purchased products within each category.

with item_counts as (
select category, item_purchased, count(*) as "number of purchases",
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from dbo.customer
group by category, item_purchased
)
select item_rank, category, item_purchased, "number of purchases"
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) are likely to subscribe?

select subscription_status, count(*) as "Number of Customers"
from dbo.customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue distribution of each age group?

select age_group, sum(purchase_amount) as "Total Revenue" 
from dbo.customer
group by age_group
order by "Total Revenue" desc;